title: "Orbsの話（仮）"
author: "sue445"
#theme: "sky"

meta_properties:
  og:locale: "ja_JP"
  og:type: "website"
  og:title: ""
  og:description: "の発表資料です"
  og:url: "https://sue445.github.io/circleci-user-meetup-01/#/"
  og:image: "https://sue445.github.io/circleci-user-meetup-01/images/cover.png"

meta_names:
  twitter:card: "Summary"
  twitter:site: "@sue445"
  twitter:creator: "@sue445"
  twitter:title: ""
  twitter:description: ""
  twitter:image: "https://sue445.github.io/circleci-user-meetup-01/images/cover.png"
