title: "Orbsベストプラクティス #circlecijp"
author: "sue445"
theme: "sky"

meta_properties:
  og:locale: "ja_JP"
  og:type: "website"
  og:title: "Orbsベストプラクティス #circlecijp"
  og:description: "「第1回CircleCI ユーザーコミュニティミートアップ」の発表資料です"
  og:url: "https://sue445.github.io/circleci-user-community-meetup-01/#/"
  og:image: "https://sue445.github.io/circleci-user-community-meetup-01/images/cover.png"

meta_names:
  twitter:card: "Summary"
  twitter:site: "@sue445"
  twitter:creator: "@sue445"
  twitter:title: "Orbsベストプラクティス #circlecijp"
  twitter:description: "「第1回CircleCI ユーザーコミュニティミートアップ」の発表資料です"
  twitter:image: "https://sue445.github.io/circleci-user-community-meetup-01/images/cover.png"
